index index.html index.htm default.html;

server {
	listen 8080;
	server_name localhost;
	root ./www/Pages;
	autoindex on;
	location / {
	}
	location /redirection {
		return 301 "https://www.youtube.com/watch?v=dQw4w9WgXcQ";
	}
	location /upload.html {
		limit_except GET;
	}
	location /upload {
		limit_except POST DELETE;
		upload_store ./www/Uploads;
		client_max_body_size 10M;
	}
	location /deleteme.html 
	{
		limit_except GET DELETE;
	}
	
	location /deleteme 
	{
		limit_except DELETE;
	}
	location /deleter.html 
	{
		limit_except POST GET DELETE;
	}
	
}
