index index.html index.htm default.html;

server {
	listen 8080;
	server_name localhost;
	root ./www/Pages;
	autoindex on;
	error_page 404 /Errors/404.html;
	error_page 505 /Errors/505.html;
	location / {
	}
	location /redirection {
		return 301 "https://www.youtube.com/watch?v=dQw4w9WgXcQ";
	}
	location /upload.html {
		limit_except GET;
	}
	location /upload {
		limit_except POST DELETE;
		upload_store ./www/Uploads;
		client_max_body_size 10M;
	}
	location /deleteme.html
	{
		limit_except GET DELETE;
	}

	location /CGI
	{
		root ./www;
		cgi_handler .py /usr/bin/python3;
        limit_except GET POST;
	}

	location /hola
	{
		index hola.html;
		error_page 404 /Errors/404.html;
	}

	location /deleteme
	{
		limit_except DELETE;
	}
	location /deleter.html
	{
		limit_except POST GET DELETE;
	}

}

server{
	listen 9090;
    server_name localhost;
    root ./www/OtherSite;
	location / {
	}
	location /upload {
		limit_except POST DELETE;
		upload_store ./www/Uploads;
		client_max_body_size 1k;
	}
}